<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>GFI_STP_Monitor</RootNamespace>
    <AssemblyName>GFI_STP_Monitor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuickFIXn" Version="1.11.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="stp_quickfix.cfg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
